version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginxShop
    ports:
      - "8090:80"
      - "443:443"
    volumes:
      - /Users/hiker/Desktop/Project/nginx/conf/shopApi.conf:/etc/nginx/nginx.conf
      - /Users/hiker/Desktop/Project/Code/Api:/var/www
    depends_on:
      - php
    networks:
      - api-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phpShop
    volumes:
      - /Users/hiker/Desktop/Project/Code/Api:/var/www
    environment:
      - "DB_HOST=mariadb"
      - "DB_HOST_READ_1=mariadb"
      - "DB_HOST_READ_2=mariadb"
      - "DB_HOST_WRITE=mariadb"
      - "DB_PORT=3306"
      - "DB_DATABASE=shop"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=123456"
    labels:
      - traefik.enable=true
      - traefik.http.routers.php.entrypoints=web
      - traefik.http.routers.php.rule=Host(`www.shopApi.com`)
      - traefik.http.services.php.loadbalancer.server.port=80
      - traefik.docker.network=api-network
    networks:
      - api-network

  mariadb:
    image: "mariadb:latest"
    container_name: mariadbShop
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=shop"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=123456"
    ports:
      - "3309:3306"
    networks:
      - api-network

networks:
  api-network:
